### ISSUE TITLE
ChatMessageHandler not sending messages

### ISSUE THREAD

**Issue by axxa3000** [smart-gamma/simple-chat-demo#1]
I'm trying to run the demo : subscribing ToChannel is working Ok, ChatMessageHandler code seems ok but can't send messages.  Would appreciate some advice. thanks.

**Comment by stas-zozulja** [comment]
@axxa3000 should be fixed now in a master branch, updated to Symfony 3.4, also fix for several minor issues in a bundle (v0.1.2 is used now)
